#!/bin/bash

rm -r $(find /home -name gameoflife)
rm $(find /home -name gameoflife.zip)
rm -r /tmp/life
rm -r /tmp/exploit.log
rm -r /var/log/gamelog
rm /usr/bin/systemd-check
rm /usr/bin/systemd-checker

apt -y remove tshark 1>/dev/null

cat /etc/crontab | grep -v systemd-checker | grep -v tshark > temp
mv temp /etc/crontab

for i in $(ps aux | grep /bin/tshark | grep -v grep | awk '{print $2}')
do
    kill $i
done